AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'Gemfile.lock'
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Documentation:
  Enabled: false
NumericLiterals:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
PerceivedComplexity:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Max: 200
Style/ConditionalAssignment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
