inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rake

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/*"
    - "Gemfile.lock"
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Style/ConditionalAssignment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

# need to explicity enable this because rubocop-rails-omakase disables it
Layout/BlockAlignment:
  Enabled: true
