--- !ruby/object:OpenStruct
table:
  :default_country: "US"
  :site_name: "Paul’s Brooklyn House Concerts"
  :meta_description: "Paul’s house concerts in Brooklyn, New York. Private shows featuring talented singer-songwriters."
  :meta_keywords: "Brooklyn, New York, Music, Live, Concert, Concerts, House Concert, Singer Songwriter, Folk, Acoustic, Unplugged"
  :facebook_app_id: "557776301028129"
  :facebook_page_slug: BrooklynHouseConcerts
  :twitter_name: HouseConcertsBK
  :twitter_id: "3317563834"
  :google_analytics_id: "UA-1895263-1"

  :venue: !ruby/object:OpenStruct
    table:
      :min_capacity: 10
      :max_capacity: 100

  :show: !ruby/object:OpenStruct
    table:
      :min_price: 0
      :max_price: 100
      :min_seats: 1
      :max_seats: 4
      :status: !map:HashWithIndifferentAccess
        "sold out": S
        "waitlisted": W
        "confirmed": G
        "unconfirmed": U
        "cancelled": C

  :person: !ruby/object:OpenStruct
    table:
      :status: !map:HashWithIndifferentAccess
        "active": "A"
        "bouncing": "B"
        "moved": "M"
        "removed": "R"
        "deleted": "D"
        "vacation": "V"

  :rsvp: !ruby/object:OpenStruct
    table:
      :response: !map:HashWithIndifferentAccess
        "yes": "Y"
        "no": "N"
      :confirmed: !map:HashWithIndifferentAccess
        "yes": "Y"
        "no": "N"
        "waitlisted": "W"
