---
:default_country: "US"
:site_name: "Paul’s Brooklyn House Concerts"
:meta_description: "Paul’s house concerts in Brooklyn, New York. Private shows featuring talented singer-songwriters."
:meta_keywords: "Brooklyn, New York, Music, Live, Concert, Concerts, House Concert, Singer Songwriter, Folk, Acoustic, Unplugged"
:google_analytics_id: "G-1RMTZBQMTP"
:default_venue_group: 2
:invites_from: '"Paul Schreiber" <paul@houseconcerts.nyc>'
:arrival_minutes: 30
:show_duration: 2

:exception_list:
  :first_names:
    - "danah"
  :last_names:
    - "boyd"

:venue:
  :min_capacity: 10
  :max_capacity: 100

:show:
  :min_price: 0
  :max_price: 100
  :min_seats: 1
  :max_seats: 4
