name: Auto approve

on:
  pull_request:

jobs:
  auto-approve:
    name: Auto approve
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Approve Dependabot pull request
        uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7
