name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  check-for-cc:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Check for Conventional Commits
        uses: agenthunt/conventional-commit-checker-action@v2.0.1
