name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  merge_group:

permissions:
  contents: read

jobs:
  check-for-cc:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check for Conventional Commits
        uses: agenthunt/conventional-commit-checker-action@f1823f632e95a64547566dcd2c7da920e67117ad # v2.0.1
